imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Default.yaml" }

editor:
  externalPlugins:
    placeholder:
      resource: 'EXT:placeholder/Resources/Public/JavaScript/CkEditor/placeholder/plugin.js'

  config:
    extraPlugins:
      - placeholder
